### ISSUE TITLE
Problems running swagger-typescript-api cli in unix environment.

### ISSUE THREAD

**Issue by gtolarc** [acacode/swagger-typescript-api#423] opened 2022-10-20 02:32 UTC
Starting with v10.0.2, when running swagger-typescript-api cli in unix environment, the following error occurs.
> env: node\r: No such file or directory

Perhaps the published swagger-typescript-api cli file is saved in dos format, and it would be better to save it in unix format.
(Maybe it's a problem with the deployment environment.)

I hope it will be reflected soon.

**Comment by craigmiller160** [comment] 2022-10-20 17:22
I also have this issue. I feel like the filepaths are using CRLF internally, which is not good. It should be using platform-independent separators.

**Comment by js2me** [comment] 2022-10-21 07:30
@gtolarc @craigmiller160 
Cannot reproduce on macOS Monterey 12.1 (notebook), with node 14.17.4 and npm 8.5.5   
Need more information how to reproduce this problem

**Comment by gtolarc** [comment] 2022-10-21 07:37
@js2me The problem is that the swagger-typescript-api CLI file downloaded from npm is saved in dos format.
macOS Monterey 12.6 (m1), node v18.11.0 (npm v8.19.2)

**Comment by JavaScriptJohn** [comment] 2022-10-21 14:53
Same problem: Xubuntu 22.10

**Comment by js2me** [comment] 2022-10-21 21:36
Should be fixed in 10.0.3, please reopen if it will not been fixed

**Closed by js2me** 2022-10-21 21:36 UTC
